"""empty message

Revision ID: 3dc72ec3bc2d
Revises: 3eb35b7f4ae9
Create Date: 2018-08-06 12:43:31.687159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc72ec3bc2d'
down_revision = '3eb35b7f4ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watering_event', schema=None) as batch_op:
        batch_op.drop_column('also_in_progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watering_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('also_in_progress', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
