"""empty message

Revision ID: 3eb35b7f4ae9
Revises: 
Create Date: 2018-08-06 12:34:33.858077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb35b7f4ae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('operational', 'suspended', name='state'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(length=10), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('is_on', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(length=10), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='days'), nullable=True),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('stop', sa.Time(), nullable=True),
    sa.Column('valves_', sa.String(length=10), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.Column('also_in_progress', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watering_event')
    op.drop_table('sensor_reading')
    op.drop_table('relay')
    op.drop_table('app_state')
    # ### end Alembic commands ###
