"""empty message

Revision ID: 40e814a5be99
Revises: 7aad5e40a02b
Create Date: 2018-08-12 14:06:52.283055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e814a5be99'
down_revision = '7aad5e40a02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valves_', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.drop_column('valves_')

    # ### end Alembic commands ###
