"""empty message

Revision ID: 7aad5e40a02b
Revises: 3dc72ec3bc2d
Create Date: 2018-08-06 13:26:51.535819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aad5e40a02b'
down_revision = '3dc72ec3bc2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manually_modified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_state', schema=None) as batch_op:
        batch_op.drop_column('manually_modified')

    # ### end Alembic commands ###
